name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t retina-ai .

    - name: Save image and zip
      run: |
        docker save retina-ai -o retina_ai_image.tar
        zip retina_ai_image.zip retina_ai_image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: retina_ai_docker
        path: retina_ai_image.zip