name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create service account key file
      run: echo "${{ secrets.GDRIVE_SERVICE_KEY }}" > gdrive_key.json

    - name: Download model weights
      run: bash retina_ai_retfound_project/weights_download.sh

    - name: Remove key for security
      run: rm gdrive_key.json

    - name: Build Docker image
      run: docker build -t retina-ai ./retina_ai_retfound_project

    - name: Save image and zip
      run: |
        docker save retina-ai -o retina_ai_image.tar
        zip retina_ai_image.zip retina_ai_image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: retina_ai_docker
        path: retina_ai_image.zip